"""add_video_metadata_and_notes

Revision ID: 10da073934c5
Revises: 64d3cbce25d3
Create Date: 2026-06-20 11:17:18.802058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10da073934c5'
down_revision: Union[str, None] = '64d3cbce25d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('channel_name', sa.String(length=255), nullable=True))
    op.add_column('videos', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('thumbnail_url', sa.String(length=1000), nullable=True))
    op.add_column('videos', sa.Column('user_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'user_notes')
    op.drop_column('videos', 'thumbnail_url')
    op.drop_column('videos', 'duration')
    op.drop_column('videos', 'channel_name')
    # ### end Alembic commands ###
